#!/usr/bin/env bash

function bootstrap {
  local shome="${_tunnelblick_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      brew cask install tunnelblick
      ;;
  esac
}

bootstrap
