#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      block compile dmg 'https://tunnelblick.net/release/Tunnelblick_3.6.0a_build_4543.4546.dmg'
      open "/Volumes/Tunnelblick/Tunnelblick.app"
      ;;
  esac
}

bootstrap
