#!/usr/bin/env bash

function home_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      true
      ;;
    *)
      return 0
      ;;
  esac

  exec 1>/dev/null 2>&1

  for a in tunnelblick; do
    if ! brew cask list $a; then
      return 1
    fi
  done
}

home_bootstrap "$@"
