#!/usr/bin/env bash

function _tunnelblick_profile {
  local shome="${_tunnelblick_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
}

_tunnelblick_profile
